// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1vQuo3AHvIj4jxcw_J6ugAlph2i0WqgI',
    appId: '1:213421486840:web:5235613206f61c26e2410d',
    messagingSenderId: '213421486840',
    projectId: 'ca14-8926c',
    authDomain: 'ca14-8926c.firebaseapp.com',
    storageBucket: 'ca14-8926c.firebasestorage.app',
    measurementId: 'G-MQNC11V0G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL2OjAqCEs211WAnB2I7HqkH7OH1VmAso',
    appId: '1:213421486840:android:19c4c99a5ea07821e2410d',
    messagingSenderId: '213421486840',
    projectId: 'ca14-8926c',
    storageBucket: 'ca14-8926c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvKHxkjc-q47RfZoSyEBSMvXO_X-DLnI4',
    appId: '1:213421486840:ios:eaed1d97c8bc4cdde2410d',
    messagingSenderId: '213421486840',
    projectId: 'ca14-8926c',
    storageBucket: 'ca14-8926c.firebasestorage.app',
    iosBundleId: 'com.example.ca14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvKHxkjc-q47RfZoSyEBSMvXO_X-DLnI4',
    appId: '1:213421486840:ios:eaed1d97c8bc4cdde2410d',
    messagingSenderId: '213421486840',
    projectId: 'ca14-8926c',
    storageBucket: 'ca14-8926c.firebasestorage.app',
    iosBundleId: 'com.example.ca14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1vQuo3AHvIj4jxcw_J6ugAlph2i0WqgI',
    appId: '1:213421486840:web:b38273f4c82767b9e2410d',
    messagingSenderId: '213421486840',
    projectId: 'ca14-8926c',
    authDomain: 'ca14-8926c.firebaseapp.com',
    storageBucket: 'ca14-8926c.firebasestorage.app',
    measurementId: 'G-8HFHJ0RDY1',
  );
}
